apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website
spec:
  # Reduce to 1 replica to ensure it can run on limited hardware
  replicas: 1
  selector:
    matchLabels:
      app: my-website
  template:
    metadata:
      labels:
        app: my-website
    spec:
      containers:
        - name: my-website
          image: "hoffeloffe/my-portfolio:latest"
          ports:
            - containerPort: 3000
          # Simple TCP check to verify the port is open
          startupProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 30
          # Simple TCP check for readiness
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          # Ultra lightweight resources for Raspberry Pi
          resources:
            limits:
              memory: "150Mi"
              cpu: "200m"
            requests:
              memory: "50Mi"
              cpu: "50m"
          # Avoid repeatedly pulling the same image
          imagePullPolicy: IfNotPresent
          # Environment variables
          env:
            - name: NODE_ENV
              value: "production"
